version: "3"
services:
  # MySQL
  db:
    container_name: drf_sample_mysql
    build:
      context: ./.docker/db
      dockerfile: Dockerfile
    command:
      - "mysqld"
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    volumes:
      - db-volume:/var/lib/mysql

  # Nginx
  web:
    container_name: drf_sample_nginx
    build:
      context: ./.docker/web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

  # Django REST framework
  api:
    container_name: drf_sample_api
    env_file: .env
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    entrypoint: >
      /bin/bash -c './docker/app/wait-for-it.sh --timeout=60 db:3306; "$${@}"' bash
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/var/www/drf-sample-api
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db-volume:
