version: "3"
services:
  # PostgreSQL
  postgres_db:
    container_name: sample_postgres_db
    image: postgres:13-bullseye
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Django REST framework
  api:
    container_name: sample_django_rest_container
    env_file: ./.env
    build: .
    command: python3 src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    tty: true

volumes:
  postgres_data:
